fix shfmt issues with jumar

diff --git a/rel/overlays/bin/jumar b/rel/overlays/bin/jumar
--- a/rel/overlays/bin/jumar
+++ b/rel/overlays/bin/jumar
@@ -36,27 +36,26 @@ export RELEASE_BOOT_SCRIPT
 RELEASE_BOOT_SCRIPT_CLEAN="${RELEASE_BOOT_SCRIPT_CLEAN:-"start_clean"}"
 export RELEASE_BOOT_SCRIPT_CLEAN
 
-rand () {
-  dd count=1 bs=2 if=/dev/urandom 2> /dev/null | od -x | awk 'NR==1{print $2}'
+rand() {
+  dd count=1 bs=2 if=/dev/urandom 2>/dev/null | od -x | awk 'NR==1{print $2}'
 }
 
-release_distribution () {
+release_distribution() {
   case $RELEASE_DISTRIBUTION in
-    none)
-      ;;
+  none) ;;
 
-    name | sname)
-      echo "--$RELEASE_DISTRIBUTION $1"
-      ;;
+  name | sname)
+    echo "--$RELEASE_DISTRIBUTION $1"
+    ;;
 
-    *)
-      echo "ERROR: Expected sname, name, or none in RELEASE_DISTRIBUTION, got: $RELEASE_DISTRIBUTION" >&2
-      exit 1
-      ;;
+  *)
+    echo "ERROR: Expected sname, name, or none in RELEASE_DISTRIBUTION, got: $RELEASE_DISTRIBUTION" >&2
+    exit 1
+    ;;
   esac
 }
 
-export_release_sys_config () {
+export_release_sys_config() {
   DEFAULT_SYS_CONFIG="${RELEASE_SYS_CONFIG:-"$REL_VSN_DIR/sys"}"
 
   if grep -q "RUNTIME_CONFIG=true" "$DEFAULT_SYS_CONFIG.config"; then
@@ -73,61 +72,61 @@ export_release_sys_config () {
   export RELEASE_SYS_CONFIG
 }
 
-app_start () {
+app_start() {
   export_release_sys_config
   REL_EXEC="$1"
   shift
   exec "$REL_VSN_DIR/$REL_EXEC" \
-       --cookie "$RELEASE_COOKIE" \
-       $(release_distribution "$RELEASE_NODE") \
-       --erl "-mode $RELEASE_MODE" \
-       --erl-config "$RELEASE_SYS_CONFIG" \
-       --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT" \
-       --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \
-       --vm-args "$RELEASE_VM_ARGS" "$@"
+    --cookie "$RELEASE_COOKIE" \
+    $(release_distribution "$RELEASE_NODE") \
+    --erl "-mode $RELEASE_MODE" \
+    --erl-config "$RELEASE_SYS_CONFIG" \
+    --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT" \
+    --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \
+    --vm-args "$RELEASE_VM_ARGS" "$@"
 }
 
-app_eval () {
+app_eval() {
   export_release_sys_config
   script="$1"
   shift
   exec "$REL_VSN_DIR/elixir" \
-       --cookie "$RELEASE_COOKIE" \
-       --erl-config "$RELEASE_SYS_CONFIG" \
-       --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT_CLEAN" \
-       --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \
-       --vm-args "$RELEASE_VM_ARGS" \
-       --eval "$script" -- "$@"
+    --cookie "$RELEASE_COOKIE" \
+    --erl-config "$RELEASE_SYS_CONFIG" \
+    --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT_CLEAN" \
+    --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \
+    --vm-args "$RELEASE_VM_ARGS" \
+    --eval "$script" -- "$@"
 }
 
 case $1 in
-  server)
-    PHX_SERVER=true app_start "elixir" --no-halt
-    ;;
+server)
+  PHX_SERVER=true app_start "elixir" --no-halt
+  ;;
 
-  migrate)
-    app_eval "Jumar.Release.migrate"
-    ;;
+migrate)
+  app_eval "Jumar.Release.migrate"
+  ;;
 
-  iex)
-    app_start "iex" --werl
-    ;;
+iex)
+  app_start "iex" --werl
+  ;;
 
-  eval)
-    if [ -z "$2" ]; then
-      echo "ERROR: EVAL expects an expression as argument" >&2
-      exit 1
-    fi
-    shift 1
-    app_eval "$@"
-    ;;
+eval)
+  if [ -z "$2" ]; then
+    echo "ERROR: EVAL expects an expression as argument" >&2
+    exit 1
+  fi
+  shift 1
+  app_eval "$@"
+  ;;
 
-  version)
-    echo "$RELEASE_NAME $RELEASE_VSN"
-    ;;
+version)
+  echo "$RELEASE_NAME $RELEASE_VSN"
+  ;;
 
-  *)
-    echo "Usage: $(basename "$0") COMMAND [ARGS]
+*)
+  echo "Usage: $(basename "$0") COMMAND [ARGS]
 
 The known commands are:
 
@@ -138,9 +137,9 @@ The known commands are:
     version          Prints the release name and version
 " >&2
 
-    if [ -n "$1" ]; then
-      echo "ERROR: Unknown command $1" >&2
-      exit 1
-    fi
-    ;;
+  if [ -n "$1" ]; then
+    echo "ERROR: Unknown command $1" >&2
+    exit 1
+  fi
+  ;;
 esac
